- name: task level variables
  hosts: local
  connection: local
  # vars:
  #   COURSE: "Learning Devops"
  tasks:
  - name: print variables
    vars:
      COURSE: "AWS with cloud"
    ansible.builtin.debug:
      msg: "your course is: {{ COURSE }}"    