- name: demo on datatypes
  hosts: local
  connection: local
  vars:
    PROGRAM: "aws with cloud"
    DURATION: 140
    IS_TRUE: true
  DETAILS:
    MONTHS: 4
    TRAINER: "anilkumar"
  TOPICS:
  - Linux
  - Aws
  - Cloud
  tasks:
  - name: print datatypes
    ansible.builtin.debug:
      msg: |
        program: {{ PROGRAM }}
        IS_TRUE: {{ IS_TRUE }}
        trainer: {{ TRAINER }}