- name: gathering facts
  hosts: local
  connection: local
  vars:
    SIZE: "19.40 GB"
  tasks:
    - name: print facts
      ansible.builtin.debug:
       msg: "{{ ansible_facts }}"

    - name: check ec2user or not
      ansible.builtin.debug:
        msg: "yes, package manager is ec2user"
      when: ansible_facts.user_id == "ec2-user"

    - name: check system or not
      ansible.builtin.debug:
        msg: "yes, system is available"
      when: ansible_facts.system == "Linux"

# "size": "19.40 GB",
    - name: check size or not
      ansible.builtin.debug:
        msg: "disk size matched"
      when: SIZE == "19.40 GB"